---
- name: Add Admin User with weak password
  ansible.builtin.include_role:
    name: mssql_add_login
  vars:
    sql_local_login_username: admin
    sql_local_login_password: P@ssw0rd
    sql_is_domain_login: False

- name: Grant sysadmin role to admin user
  ansible.builtin.include_role:
    name: mssql_grant_role
  vars:
    mssql_role_name: sysadmin
    mssql_grantee: admin

- name: Add the BUILTIN\\Users group as a pubic login (old default)
  ansible.builtin.include_role:
    name: mssql_add_login
  vars:
    sql_local_login_username: '[BUILTIN\Users]'
    sql_is_domain_login: True

- name: Add Kerberoastable user to the local administrators group
  ansible.windows.win_group_membership:
    name: Administrators
    members:
      - '{{ ludus_domain_fqdn }}\{{ ludus_sql_svc_account_username }}'
    state: present

- name: Add Kerberoastable user to the SQL admins group
  community.windows.win_domain_group_membership:
    name: '{{ ludus_sql_admin_group }}'
    members:
      - '{{ ludus_sql_svc_account_username }}'
    state: present
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: '{{ ludus_domain_fqdn }}\{{ defaults.ad_domain_admin }}'
    ansible_become_password: '{{ defaults.ad_domain_admin_password }}'
    ansible_become_flags: "logon_type=interactive logon_flags=with_profile"