---
ludus_install_directory: /opt/ludus
ludus_sql2022_url: https://download.microsoft.com/download/3/8/d/38de7036-2433-4207-8eae-06e247e17b25/SQLServer2022-x64-ENU.iso
ludus_sql_svc_account_username: srv_sql
ludus_sql_svc_account_password: SuperDuperStrong123!