---
dependencies: []

galaxy_info:
  role_name: ludus_mssql_add_local_login
  author: Bob Van der Smissen
  description: Add a local login
  company: None :D
  license: GPLv3
  min_ansible_version: "2.10"
  platforms:
    - name: Windows
      versions:
        - "2012R2"
        - "2016"
        - "2019"
        - "2022"

  galaxy_tags:
    - windows
    - security
    - activedirectory
    - server
    - ludus